import PageMetadata from '../models/PageMetadata';
import { normalizeSlug } from './metadataHelpers';

/**
 * Normalize path to match how it's stored in database
 */
function normalizePath(path: string): string {
  if (!path) return '';
  
  // Extract slug from path if it's a product/post path
  if (path.startsWith('/products/')) {
    const slug = path.replace('/products/', '');
    return `/products/${normalizeSlug(slug)}`;
  }
  
  if (path.startsWith('/posts/')) {
    const slug = path.replace('/posts/', '');
    return `/posts/${normalizeSlug(slug)}`;
  }
  
  // For other paths, return as-is (but ensure it starts with /)
  return path.startsWith('/') ? path : `/${path}`;
}

/**
 * Sync SEO settings pages to page_metadata table
 * This is called when saving SEO settings from CMS frontend
 * CRITICAL: Also removes pages that are not in the provided array (except auto-generated ones)
 */
export async function syncSeoSettingsToPageMetadata(pages: any[]) {
  try {
    console.log(`[syncSeoSettingsToPageMetadata] Syncing ${pages.length} pages to page_metadata table`);
    
    // Get all paths from the provided pages (normalized)
    const providedPaths = new Set<string>();
    const providedPathsMap = new Map<string, any>(); // path -> page data
    
    for (const page of pages) {
      if (!page || !page.path) {
        console.warn('[syncSeoSettingsToPageMetadata] Skipping page without path:', page);
        continue;
      }
      
      const normalizedPath = normalizePath(page.path);
      providedPaths.add(normalizedPath);
      providedPathsMap.set(normalizedPath, page);
    }
    
    // Get all existing pages from database
    const allExistingPages = await PageMetadata.findAll();
    
    // Process: create/update pages from provided array
    for (const [normalizedPath, page] of providedPathsMap.entries()) {
      const existing = await PageMetadata.findOne({
        where: { path: normalizedPath },
      });
      
      const metadataData = {
        path: normalizedPath,
        title: page.title || null,
        description: page.description || null,
        og_image: page.ogImage || null,
        keywords: Array.isArray(page.keywords) && page.keywords.length > 0 ? page.keywords : null,
        enabled: page.enabled !== undefined ? page.enabled : true,
        auto_generated: page.autoGenerated !== undefined ? page.autoGenerated : false,
      };
      
      if (existing) {
        // Update existing - but preserve auto_generated flag if it's true (don't override auto-generated)
        if (existing.auto_generated && page.autoGenerated !== false) {
          // Skip updating auto-generated metadata (it will be managed by syncProductMetadataToCMS/syncPostMetadataToCMS)
          console.log(`[syncSeoSettingsToPageMetadata] Skipping auto-generated page: ${normalizedPath}`);
          continue;
        }
        
        await existing.update(metadataData);
        console.log(`[syncSeoSettingsToPageMetadata] Updated page: ${normalizedPath}`);
      } else {
        // Create new
        await PageMetadata.create(metadataData);
        console.log(`[syncSeoSettingsToPageMetadata] Created page: ${normalizedPath}`);
      }
    }
    
    // Process: delete pages that are not in provided array (but keep auto-generated ones)
    let deletedCount = 0;
    for (const existingPage of allExistingPages) {
      // Skip if page is in provided array
      if (providedPaths.has(existingPage.path)) {
        continue;
      }
      
      // Skip if page is auto-generated (don't delete auto-generated pages)
      if (existingPage.auto_generated) {
        console.log(`[syncSeoSettingsToPageMetadata] Keeping auto-generated page (not in provided array): ${existingPage.path}`);
        continue;
      }
      
      // Delete page that is not in provided array and not auto-generated
      await existingPage.destroy();
      console.log(`[syncSeoSettingsToPageMetadata] Deleted page (not in provided array): ${existingPage.path}`);
      deletedCount++;
    }
    
    console.log(`[syncSeoSettingsToPageMetadata] Successfully synced ${pages.length} pages, deleted ${deletedCount} pages`);
  } catch (error: any) {
    console.error('[syncSeoSettingsToPageMetadata] Error:', error);
    throw error;
  }
}

