import { Request, Response } from 'express';
import { AuthRequest } from '../middleware/auth';
import PageMetadata from '../models/PageMetadata';
import { normalizeSlug } from '../utils/metadataHelpers';

/**
 * Normalize path to match how it's stored in database
 */
function normalizePath(path: string): string {
  if (!path) return '';
  
  // Extract slug from path if it's a product/post path
  if (path.startsWith('/products/')) {
    const slug = path.replace('/products/', '');
    return `/products/${normalizeSlug(slug)}`;
  }
  
  if (path.startsWith('/posts/')) {
    const slug = path.replace('/posts/', '');
    return `/posts/${normalizeSlug(slug)}`;
  }
  
  // For other paths, return as-is (but ensure it starts with /)
  return path.startsWith('/') ? path : `/${path}`;
}

/**
 * Get all page metadata (for CMS admin)
 */
export const getAllPageMetadata = async (req: AuthRequest, res: Response) => {
  try {
    if (!req.user) {
      return res.status(401).json({ error: 'Unauthorized' });
    }

    const pages = await PageMetadata.findAll({
      order: [['path', 'ASC']],
    });

    // Transform to match frontend format
    const formatted = pages.map((page) => ({
      path: page.path,
      title: page.title || '',
      description: page.description || '',
      ogImage: page.og_image || '',
      keywords: page.keywords || [],
      enabled: page.enabled,
      autoGenerated: page.auto_generated,
    }));

    res.json({ pages: formatted });
  } catch (error: any) {
    console.error('[getAllPageMetadata] Error:', error);
    res.status(500).json({ error: 'Failed to load page metadata' });
  }
};

/**
 * Get single page metadata
 */
export const getPageMetadata = async (req: AuthRequest, res: Response) => {
  try {
    if (!req.user) {
      return res.status(401).json({ error: 'Unauthorized' });
    }

    const { path: rawPath } = req.params;
    const path = normalizePath(rawPath);

    const page = await PageMetadata.findOne({
      where: { path },
    });

    if (!page) {
      return res.status(404).json({ error: 'Page metadata not found' });
    }

    res.json({
      path: page.path,
      title: page.title || '',
      description: page.description || '',
      ogImage: page.og_image || '',
      keywords: page.keywords || [],
      enabled: page.enabled,
      autoGenerated: page.auto_generated,
    });
  } catch (error: any) {
    console.error('[getPageMetadata] Error:', error);
    res.status(500).json({ error: 'Failed to load page metadata' });
  }
};

/**
 * Create or update page metadata
 */
export const savePageMetadata = async (req: AuthRequest, res: Response) => {
  try {
    if (!req.user) {
      return res.status(401).json({ error: 'Unauthorized' });
    }

    const { path: rawPath, title, description, ogImage, keywords, enabled, autoGenerated } = req.body;
    const path = normalizePath(rawPath);

    if (!path) {
      return res.status(400).json({ error: 'Path is required' });
    }

    // Check if page exists
    const existing = await PageMetadata.findOne({
      where: { path },
    });

    const metadataData = {
      path,
      title: title || null,
      description: description || null,
      og_image: ogImage || null,
      keywords: Array.isArray(keywords) && keywords.length > 0 ? keywords : null,
      enabled: enabled !== undefined ? enabled : true,
      auto_generated: autoGenerated !== undefined ? autoGenerated : false,
    };

    if (existing) {
      // Update existing
      // If it's auto-generated, only allow update if explicitly setting autoGenerated to false (making it custom)
      if (existing.auto_generated && autoGenerated !== false) {
        return res.status(403).json({ 
          error: 'Cannot update auto-generated metadata. Set autoGenerated to false to make it custom.' 
        });
      }
      
      await existing.update(metadataData);
      res.json({ message: 'Page metadata updated', path });
    } else {
      // Create new
      await PageMetadata.create(metadataData);
      res.json({ message: 'Page metadata created', path });
    }
  } catch (error: any) {
    console.error('[savePageMetadata] Error:', error);
    if (error.name === 'SequelizeUniqueConstraintError') {
      return res.status(409).json({ error: 'Page metadata with this path already exists' });
    }
    res.status(500).json({ error: 'Failed to save page metadata' });
  }
};

/**
 * Delete page metadata
 */
export const deletePageMetadata = async (req: AuthRequest, res: Response) => {
  try {
    if (!req.user) {
      return res.status(401).json({ error: 'Unauthorized' });
    }

    const { path: rawPath } = req.params;
    const path = normalizePath(rawPath);

    const page = await PageMetadata.findOne({
      where: { path },
    });

    if (!page) {
      return res.status(404).json({ error: 'Page metadata not found' });
    }

    // Don't allow deleting auto-generated metadata (it will be recreated)
    if (page.auto_generated) {
      return res.status(403).json({ 
        error: 'Cannot delete auto-generated metadata. It will be recreated automatically.' 
      });
    }

    await page.destroy();
    res.json({ message: 'Page metadata deleted', path });
  } catch (error: any) {
    console.error('[deletePageMetadata] Error:', error);
    res.status(500).json({ error: 'Failed to delete page metadata' });
  }
};








