/**
 * Script to create metadata for /about page
 * 
 * Usage: npx ts-node src/scripts/createAboutMetadata.ts
 */

import sequelize from '../config/database';

const DEFAULTS = {
  seo: {
    home: { title: 'Banyco', description: '', ogImage: '', slug: '/' },
    pages: [],
  },
};

async function createAboutMetadata() {
  try {
    console.log('🚀 Creating metadata for /about page...\n');

    // 1. Fetch current SEO settings
    const [seoRow] = await sequelize.query(
      'SELECT value FROM settings WHERE namespace = :ns',
      {
        type: 'SELECT' as any,
        replacements: { ns: 'seo' },
      }
    ) as any[];

    const seoSettings = seoRow?.[0]?.value ?? DEFAULTS.seo;
    const existingPages = seoSettings.pages || [];

    // 2. Check if /about metadata already exists
    const existingAbout = existingPages.find((p: any) => p.path === '/about');
    
    if (existingAbout) {
      console.log('ℹ️  Metadata for /about already exists:');
      console.log('   Title:', existingAbout.title);
      console.log('   Description:', existingAbout.description?.substring(0, 50) + '...');
      console.log('   Enabled:', existingAbout.enabled !== false);
      console.log('\n💡 To update, please use CMS Admin → Settings → SEO & Meta');
      return;
    }

    // 3. Create new metadata for /about
    const aboutMetadata = {
      path: '/about',
      title: 'Về Chúng Tôi - Banyco Spa Solutions',
      description: 'Giới thiệu Banyco – đối tác cung cấp giải pháp & thiết bị spa chuyên nghiệp, đồng hành phát triển vận hành và tối ưu hoá lợi nhuận.',
      ogImage: '/images/og-about.jpg',
      keywords: ['Banyco', 'Spa Solutions', 'Thiết bị spa', 'Giải pháp spa'],
      enabled: true,
      autoGenerated: false, // Custom metadata, not auto-generated
    };

    // 4. Add to pages array
    existingPages.push(aboutMetadata);

    // 5. Save to settings
    const updatedSettings = {
      ...seoSettings,
      pages: existingPages,
    };

    await sequelize.query(
      `INSERT INTO settings (namespace, value, updated_at)
       VALUES (:ns, :val::jsonb, NOW())
       ON CONFLICT (namespace) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW()`,
      {
        type: 'INSERT' as any,
        replacements: {
          ns: 'seo',
          val: JSON.stringify(updatedSettings),
        },
      }
    );

    console.log('✅ Created metadata for /about page:');
    console.log('   Path:', aboutMetadata.path);
    console.log('   Title:', aboutMetadata.title);
    console.log('   Description:', aboutMetadata.description);
    console.log('   OG Image:', aboutMetadata.ogImage);
    console.log('\n💡 You can now customize this metadata in CMS Admin → Settings → SEO & Meta');
  } catch (error) {
    console.error('❌ Error creating metadata:', error);
    throw error;
  }
}

// Run the script
createAboutMetadata()
  .then(() => {
    console.log('\n✅ Script completed successfully');
    process.exit(0);
  })
  .catch((error) => {
    console.error('\n❌ Script failed:', error);
    process.exit(1);
  })
  .finally(async () => {
    await sequelize.close();
  });














