import sequelize from '../config/database';
import PageMetadata from '../models/PageMetadata';
import { normalizeSlug } from '../utils/metadataHelpers';

/**
 * Normalize path to match how it's stored in database
 */
function normalizePath(path: string): string {
  if (!path) return '';
  
  if (path.startsWith('/products/')) {
    const slug = path.replace('/products/', '');
    return `/products/${normalizeSlug(slug)}`;
  }
  
  if (path.startsWith('/posts/')) {
    const slug = path.replace('/posts/', '');
    return `/posts/${normalizeSlug(slug)}`;
  }
  
  return path.startsWith('/') ? path : `/${path}`;
}

/**
 * Migrate page metadata from settings JSONB to page_metadata table
 */
async function migratePageMetadata() {
  try {
    await sequelize.authenticate();
    console.log('✅ Database connected');

    // 1. Read from settings table
    const [seoRow] = await sequelize.query(
      'SELECT value FROM settings WHERE namespace = :ns',
      {
        type: 'SELECT' as any,
        replacements: { ns: 'seo' },
      }
    ) as any[];

    if (!seoRow || seoRow.length === 0 || !seoRow[0]?.value) {
      console.log('⚠️  No SEO settings found in settings table');
      return;
    }

    const seoSettings = seoRow[0].value;
    const pages = seoSettings.pages || [];

    if (pages.length === 0) {
      console.log('⚠️  No pages found in SEO settings');
      return;
    }

    console.log(`📦 Found ${pages.length} pages in settings to migrate`);

    // 2. Migrate each page to page_metadata table
    let migrated = 0;
    let skipped = 0;
    let errors = 0;

    for (const page of pages) {
      if (!page || !page.path) {
        console.warn('⚠️  Skipping page without path:', page);
        skipped++;
        continue;
      }

      try {
        const normalizedPath = normalizePath(page.path);

        // Check if already exists
        const existing = await PageMetadata.findOne({
          where: { path: normalizedPath },
        });

        if (existing) {
          console.log(`⏭️  Page already exists: ${normalizedPath}`);
          skipped++;
          continue;
        }

        // Create new
        await PageMetadata.create({
          path: normalizedPath,
          title: page.title || null,
          description: page.description || null,
          og_image: page.ogImage || null,
          keywords: Array.isArray(page.keywords) && page.keywords.length > 0 ? page.keywords : null,
          enabled: page.enabled !== undefined ? page.enabled : true,
          auto_generated: page.autoGenerated !== undefined ? page.autoGenerated : false,
        });

        console.log(`✅ Migrated: ${normalizedPath}`);
        migrated++;
      } catch (error: any) {
        console.error(`❌ Error migrating page ${page.path}:`, error.message);
        errors++;
      }
    }

    console.log('\n📊 Migration Summary:');
    console.log(`   ✅ Migrated: ${migrated}`);
    console.log(`   ⏭️  Skipped: ${skipped}`);
    console.log(`   ❌ Errors: ${errors}`);
    console.log(`   📦 Total: ${pages.length}`);

    await sequelize.close();
  } catch (error: any) {
    console.error('❌ Migration failed:', error);
    process.exit(1);
  }
}

// Run migration
migratePageMetadata();








