import { Router } from 'express';
import sequelize from '../config/database';

const router = Router();

// Debug endpoint to check SEO data
router.get('/debug-seo', async (req, res) => {
  try {
    const [seoRow] = await sequelize.query(
      'SELECT value FROM settings WHERE namespace = :ns',
      {
        type: 'SELECT' as any,
        replacements: { ns: 'seo' },
      }
    ) as any[];

    const seoSettings = seoRow?.[0]?.value || { pages: [] };
    const pages = seoSettings.pages || [];

    res.json({
      totalPages: pages.length,
      rawSettings: seoSettings,
      pages: pages.map((p: any) => ({
        path: p.path,
        title: p.title,
        description: p.description?.substring(0, 50),
        enabled: p.enabled,
        autoGenerated: p.autoGenerated,
        ogImage: p.ogImage,
      })),
    });
  } catch (error: any) {
    res.status(500).json({ error: error.message });
  }
});

// Test specific path
router.get('/test-path/:path(*)', async (req, res) => {
  try {
    let { path } = req.params;
    
    // Normalize path
    if (path.includes('?')) {
      path = path.split('?')[0];
    }
    path = path.replace(/\/+$/, '') || '/';
    
    const [seoRow] = await sequelize.query(
      'SELECT value FROM settings WHERE namespace = :ns',
      {
        type: 'SELECT' as any,
        replacements: { ns: 'seo' },
      }
    ) as any[];

    const seoSettings = seoRow?.[0]?.value || { pages: [] };
    const existingPages = seoSettings.pages || [];

    const matches = existingPages.map((p: any) => {
      const pagePath = (p.path || '').replace(/\/+$/, '') || '/';
      const normalizedRequestPath = path.replace(/\/+$/, '') || '/';
      return {
        pagePath,
        requestPath: normalizedRequestPath,
        matches: pagePath.toLowerCase() === normalizedRequestPath.toLowerCase(),
        enabled: p.enabled,
        page: p,
      };
    });

    res.json({
      requestedPath: req.params.path,
      normalizedPath: path,
      matches,
      found: matches.find(m => m.matches && m.enabled !== false),
    });
  } catch (error: any) {
    res.status(500).json({ error: error.message });
  }
});

export default router;

