'use client';

import { useEffect, useState } from 'react';
import { ArrowLeft, Save, Plus, Edit, Trash2, X } from 'lucide-react';
import Link from 'next/link';
import axios from 'axios';
import { toast } from 'sonner';
import MediaPicker from '@/components/MediaPicker';
import { getAssetUrl, buildApiUrl } from '@/lib/api';

export default function SEOPage() {
  const [seo, setSeo] = useState<any>({ pages: [] });
  const [saving, setSaving] = useState(false);
  const [editingPageIndex, setEditingPageIndex] = useState<number | null>(null);
  const [pagePickerOpen, setPagePickerOpen] = useState(false);
  const [currentPageImage, setCurrentPageImage] = useState<string>('');

  const fetchSeo = async () => {
    try {
      const res = await axios.get<any>(buildApiUrl('/api/settings/seo'), { withCredentials: true });
      const value = res.data?.value ?? { pages: [] };
      setSeo(value);
    } catch (e: any) {
      console.error('Failed to fetch SEO settings:', e);
    }
  };

  useEffect(() => {
    fetchSeo();
  }, []);

  const saveSeo = async () => {
    if (saving) {
      console.log('[SEO] Already saving, skipping...');
      return;
    }
    
    console.log('[SEO] Starting save, current seo state:', seo);
    
    // Validate before saving
    const pages = seo.pages || [];
    console.log('[SEO] Total pages to save:', pages.length);
    
    const invalidPages = pages.filter((p: any) => {
      if (p.autoGenerated) return false; // Skip validation for auto-generated pages
      const invalid = !p.path || !p.path.startsWith('/') || !p.title;
      if (invalid) {
        console.log('[SEO] Invalid page found:', { path: p.path, title: p.title, enabled: p.enabled });
      }
      return invalid;
    });
    
    if (invalidPages.length > 0) {
      console.error('[SEO] Validation failed:', invalidPages);
      toast.error(`Có ${invalidPages.length} trang chưa hợp lệ. Vui lòng kiểm tra Path (phải bắt đầu bằng /) và Title.`);
      return;
    }
    
    // Normalize paths before saving
    const normalizedSeo = {
      ...seo,
      pages: pages.map((p: any) => {
        if (p.autoGenerated) return p; // Don't normalize auto-generated pages
        let normalizedPath = (p.path || '').trim();
        if (normalizedPath && !normalizedPath.startsWith('/')) {
          normalizedPath = '/' + normalizedPath;
        }
        if (normalizedPath.length > 1) {
          normalizedPath = normalizedPath.replace(/\/+$/, '');
        }
        return { ...p, path: normalizedPath };
      }),
    };
    
    console.log('[SEO] Normalized SEO data:', JSON.stringify(normalizedSeo, null, 2));
    
    setSaving(true);
    try {
      const apiUrl = buildApiUrl('/api/settings/seo');
      console.log('[SEO] Calling API:', apiUrl);
      console.log('[SEO] Request payload:', JSON.stringify(normalizedSeo, null, 2));
      
      const response = await axios.put(apiUrl, normalizedSeo, { withCredentials: true });
      console.log('[SEO] Save response:', response.data);
      toast.success('Đã lưu cài đặt SEO');
      await fetchSeo();
    } catch (e: any) {
      console.error('[SEO] Save error:', e);
      console.error('[SEO] Error response:', e.response?.data);
      console.error('[SEO] Error message:', e.message);
      toast.error(e.response?.data?.error || e.message || 'Lưu thất bại');
    } finally {
      setSaving(false);
    }
  };

  // Filter pages - only show static pages (no auto-generated or dynamic pages)
  const staticPages = (seo.pages || []).filter((p: any) => {
    if (p.autoGenerated) return false;
    if (p.path?.includes(':')) return false;
    // Include new pages without path (they will be static)
    if (!p.path && p._tempId) return true;
    return true;
  });

  const renderPageList = (pages: any[], type: 'static' | 'dynamic') => (
    <div className="space-y-4">
      {pages.map((page: any, index: number) => {
        // Find index by path or temp ID (more reliable than reference comparison)
        const originalIndex = seo.pages?.findIndex((p: any) => {
          // Match by path if both have paths
          if (p.path && page.path && p.path === page.path) {
            return true;
          }
          // Match by temp ID for new pages
          if (p._tempId && page._tempId && p._tempId === page._tempId) {
            return true;
          }
          // Fallback: match by reference (for pages without path or tempId)
          return p === page;
        }) ?? -1;
        
        if (originalIndex === -1) {
          console.warn('[SEO] Could not find page in seo.pages:', page);
          return null;
        }

        const isEditing = editingPageIndex === originalIndex;

        return (
          <div key={originalIndex} className="border border-border rounded-lg p-4 bg-background">
            {isEditing ? (
              // Edit mode
              <div className="space-y-4">
                <div className="flex items-center justify-between">
                  <h4 className="font-medium text-foreground">Chỉnh sửa metadata</h4>
                  <button
                    onClick={() => {
                      setEditingPageIndex(null);
                      setPagePickerOpen(false);
                    }}
                    className="text-muted-foreground hover:text-foreground"
                  >
                    <X className="w-4 h-4" />
                  </button>
                </div>
                <div>
                  <label className="block text-sm font-medium text-foreground mb-2">Path *</label>
                  <input
                    type="text"
                    value={page.path || ''}
                    onChange={(e) => {
                      // Normalize path: ensure it starts with / and remove trailing slash
                      let normalizedPath = e.target.value.trim();
                      if (normalizedPath && !normalizedPath.startsWith('/')) {
                        normalizedPath = '/' + normalizedPath;
                      }
                      // Remove trailing slash (except for root)
                      if (normalizedPath.length > 1) {
                        normalizedPath = normalizedPath.replace(/\/+$/, '');
                      }
                      
                      const newPages = [...(seo.pages || [])];
                      newPages[originalIndex] = { ...newPages[originalIndex], path: normalizedPath };
                      setSeo({ ...seo, pages: newPages });
                    }}
                    placeholder="/products, /posts, /about, /products/slug..."
                    className="w-full px-4 py-2 rounded-lg border border-input bg-background text-foreground text-sm"
                    disabled={page.autoGenerated}
                  />
                  <p className="text-xs text-muted-foreground mt-1">Đường dẫn trang (ví dụ: /products, /posts/digital-marketing-guide). Phải bắt đầu bằng /</p>
                  {page.autoGenerated && (
                    <p className="text-xs text-blue-500 mt-1">⚠️ Trang này được tự động tạo, path không thể chỉnh sửa</p>
                  )}
                </div>
                <div>
                  <label className="block text-sm font-medium text-foreground mb-2">Title *</label>
                  <input
                    type="text"
                    value={page.title || ''}
                    onChange={(e) => {
                      const newPages = [...(seo.pages || [])];
                      newPages[originalIndex] = { ...newPages[originalIndex], title: e.target.value };
                      setSeo({ ...seo, pages: newPages });
                    }}
                    placeholder="Tiêu đề trang"
                    className="w-full px-4 py-2 rounded-lg border border-input bg-background text-foreground text-sm"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-foreground mb-2">Description</label>
                  <textarea
                    rows={3}
                    value={page.description || ''}
                    onChange={(e) => {
                      const newPages = [...(seo.pages || [])];
                      newPages[originalIndex] = { ...newPages[originalIndex], description: e.target.value };
                      setSeo({ ...seo, pages: newPages });
                    }}
                    placeholder="Mô tả trang (hiển thị khi share)"
                    className="w-full px-4 py-2 rounded-lg border border-input bg-background text-foreground text-sm"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-foreground mb-2">OG Image</label>
                  <div className="flex items-center gap-4">
                    {page.ogImage && (
                      <div className="relative">
                        <img
                          src={getAssetUrl(page.ogImage)}
                          alt="OG Image"
                          className="w-32 h-20 object-cover rounded border border-border"
                          onError={(e) => {
                            console.error('[SEO] Failed to load image:', page.ogImage);
                            console.error('[SEO] Full URL:', getAssetUrl(page.ogImage));
                            // Show placeholder instead of hiding
                            (e.target as HTMLImageElement).src = 'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" width="128" height="80"%3E%3Crect width="128" height="80" fill="%23ddd"/%3E%3Ctext x="50%25" y="50%25" text-anchor="middle" dy=".3em" fill="%23999"%3EImage%3C/text%3E%3C/svg%3E';
                          }}
                          onLoad={() => {
                            console.log('[SEO] Image loaded successfully:', getAssetUrl(page.ogImage));
                          }}
                        />
                      </div>
                    )}
                    <button
                      onClick={() => {
                        setCurrentPageImage(page.ogImage || '');
                        setPagePickerOpen(true);
                      }}
                      className="px-4 py-2 bg-primary text-primary-foreground rounded-lg text-sm hover:bg-primary/90"
                    >
                      {page.ogImage ? 'Đổi ảnh' : 'Chọn ảnh'}
                    </button>
                    {page.ogImage && (
                      <button
                        onClick={() => {
                          const newPages = [...(seo.pages || [])];
                          newPages[originalIndex] = { ...newPages[originalIndex], ogImage: '' };
                          setSeo({ ...seo, pages: newPages });
                        }}
                        className="px-4 py-2 bg-destructive text-destructive-foreground rounded-lg text-sm hover:bg-destructive/90"
                      >
                        Xóa ảnh
                      </button>
                    )}
                  </div>
                  <p className="text-xs text-muted-foreground mt-1">Ảnh hiển thị khi share (khuyến nghị: 1200x630px)</p>
                </div>
                <div className="flex items-center gap-4">
                  <label className="flex items-center gap-2 cursor-pointer">
                    <input
                      type="checkbox"
                      checked={page.enabled !== false}
                      onChange={(e) => {
                        const newPages = [...(seo.pages || [])];
                        newPages[originalIndex] = { ...newPages[originalIndex], enabled: e.target.checked };
                        setSeo({ ...seo, pages: newPages });
                      }}
                      className="w-4 h-4"
                    />
                    <span className="text-sm text-foreground">Kích hoạt</span>
                  </label>
                  {page.autoGenerated && (
                    <span className="text-xs px-2 py-1 bg-blue-500/20 text-blue-500 rounded">Tự động tạo</span>
                  )}
                </div>
                <div className="flex gap-2">
                  <button
                    onClick={() => {
                      setEditingPageIndex(null);
                      setPagePickerOpen(false);
                    }}
                    className="px-4 py-2 bg-muted text-muted-foreground rounded-lg text-sm hover:bg-muted/80"
                  >
                    Hủy
                  </button>
                  <button
                    onClick={async () => {
                      // Validate path before saving
                      const currentPage = seo.pages?.[originalIndex];
                      console.log('[SEO Edit] Current page:', currentPage);
                      
                      if (!currentPage?.path || !currentPage.path.startsWith('/')) {
                        toast.error('Path phải bắt đầu bằng / (ví dụ: /about)');
                        return;
                      }
                      if (!currentPage?.title) {
                        toast.error('Title là bắt buộc');
                        return;
                      }
                      
                      // Remove tempId before saving
                      const pageToSave = { ...currentPage };
                      delete pageToSave._tempId;
                      const newPages = [...(seo.pages || [])];
                      newPages[originalIndex] = pageToSave;
                      setSeo({ ...seo, pages: newPages });
                      
                      console.log('[SEO Edit] Saving page, current seo state:', seo);
                      await saveSeo();
                      setEditingPageIndex(null);
                      setPagePickerOpen(false);
                    }}
                    className="px-4 py-2 bg-primary text-primary-foreground rounded-lg text-sm hover:bg-primary/90"
                  >
                    Lưu
                  </button>
                </div>
              </div>
            ) : (
              // View mode
              <div>
                <div className="flex items-center justify-between mb-2">
                  <div className="flex-1">
                    <div className="flex items-center gap-2">
                      <span className="font-medium text-foreground">{page.path || '(Chưa có path)'}</span>
                      {page.autoGenerated && (
                        <span className="text-xs px-2 py-1 bg-blue-500/20 text-blue-500 rounded">Tự động</span>
                      )}
                      {page.enabled === false && (
                        <span className="text-xs px-2 py-1 bg-destructive/20 text-destructive rounded">Tắt</span>
                      )}
                    </div>
                    <p className="text-sm font-medium text-foreground mt-1">{page.title || '(Chưa có title)'}</p>
                    {page.description && (
                      <p className="text-xs text-muted-foreground mt-1 line-clamp-2">{page.description}</p>
                    )}
                  </div>
                  <div className="flex items-center gap-2">
                    <button
                      onClick={() => setEditingPageIndex(originalIndex)}
                      className="p-2 text-muted-foreground hover:text-foreground hover:bg-muted rounded"
                      title="Chỉnh sửa"
                    >
                      <Edit className="w-4 h-4" />
                    </button>
                    {!page.autoGenerated && (
                      <button
                        onClick={async () => {
                          if (confirm(`Bạn có chắc chắn muốn xóa metadata cho "${page.path}"?`)) {
                            const newPages = seo.pages?.filter((_: any, i: number) => i !== originalIndex) || [];
                            const updatedSeo = { ...seo, pages: newPages };
                            try {
                              await axios.put(buildApiUrl('/api/settings/seo'), updatedSeo, { withCredentials: true });
                              toast.success('Đã xóa metadata');
                              await fetchSeo();
                            } catch (e: any) {
                              toast.error(e.response?.data?.error || 'Xóa thất bại');
                            }
                          }
                        }}
                        className="p-2 text-destructive hover:bg-destructive/20 rounded"
                        title="Xóa"
                      >
                        <Trash2 className="w-4 h-4" />
                      </button>
                    )}
                  </div>
                </div>
              </div>
            )}
          </div>
        );
      })}
    </div>
  );

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-foreground">Quản lý SEO</h1>
          <p className="text-sm text-muted-foreground">Cấu hình metadata (title, description, OG image) cho các trang tĩnh. SEO cho Product và Post được quản lý trực tiếp trong form CRUD của chúng.</p>
        </div>
        <div className="flex items-center gap-2">
          <Link href="/dashboard" className="inline-flex items-center gap-2 rounded-lg border border-input bg-background px-3 py-2 text-sm hover:bg-accent hover:text-accent-foreground transition-colors">
            <ArrowLeft className="h-4 w-4" />
            Back
          </Link>
          <button
            onClick={saveSeo}
            disabled={saving}
            className="inline-flex items-center gap-2 rounded-lg bg-primary px-3 py-2 text-sm font-medium text-primary-foreground hover:bg-primary/90 transition-colors disabled:opacity-60 disabled:cursor-not-allowed"
          >
            <Save className="h-4 w-4" />
            {saving ? 'Đang lưu...' : 'Lưu tất cả'}
          </button>
        </div>
      </div>

      <div className="rounded-lg border border-border bg-card p-6 space-y-6">
        {/* Static Pages Section */}
        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <div>
              <h4 className="text-base font-semibold text-foreground">Trang tĩnh</h4>
              <p className="text-xs text-muted-foreground mt-1">
                Các trang cố định như /products, /about, /contact. Bạn có thể tạo và chỉnh sửa tự do.
              </p>
            </div>
            <button
              onClick={() => {
                const newPage = {
                  _tempId: `__new_${Date.now()}`, // Temporary ID for new pages
                  path: '',
                  title: '',
                  description: '',
                  ogImage: '',
                  keywords: [],
                  enabled: true,
                  autoGenerated: false,
                };
                const newPages = [...(seo.pages || []), newPage];
                const newIndex = newPages.length - 1;
                setSeo({ ...seo, pages: newPages });
                // Set editing mode immediately for the new page
                setEditingPageIndex(newIndex);
              }}
              className="px-4 py-2 bg-primary text-primary-foreground rounded-lg text-sm hover:bg-primary/90 flex items-center gap-2"
            >
              <Plus className="w-4 h-4" />
              <span>Thêm trang tĩnh</span>
            </button>
          </div>
          {staticPages.length > 0 ? (
            renderPageList(staticPages, 'static')
          ) : (
            <div className="border border-dashed border-border rounded-lg p-8 text-center">
              <p className="text-sm text-muted-foreground">Chưa có trang tĩnh nào. Click "Thêm trang tĩnh" để tạo.</p>
            </div>
          )}
        </div>

      </div>

      {/* Media Picker for Page OG Image */}
      {pagePickerOpen && (
        <MediaPicker
          isOpen={pagePickerOpen}
          onClose={() => setPagePickerOpen(false)}
          onSelect={(assetOrUrl) => {
            if (editingPageIndex !== null) {
              const newPages = [...(seo.pages || [])];
              // Handle both Asset object and string URL (for backward compatibility)
              if (typeof assetOrUrl === 'object' && assetOrUrl !== null) {
                // Asset object - use relative path from url or cdn_url
                const asset = assetOrUrl as any;
                console.log('[SEO] Selected asset:', asset);
                
                // Try multiple possible URL fields
                const assetUrl = asset.url || asset.cdn_url || asset.original_url || asset.sizes?.medium?.url || asset.sizes?.large?.url || '';
                console.log('[SEO] Asset URL:', assetUrl);
                
                // Convert to relative path if it's a full URL
                let relativePath = assetUrl;
                if (assetUrl.startsWith('http://') || assetUrl.startsWith('https://')) {
                  try {
                    const urlObj = new URL(assetUrl);
                    relativePath = urlObj.pathname;
                  } catch (e) {
                    console.error('[SEO] Failed to parse URL:', e);
                    relativePath = assetUrl;
                  }
                }
                
                console.log('[SEO] Saving ogImage as:', relativePath);
                newPages[editingPageIndex] = { ...newPages[editingPageIndex], ogImage: relativePath || assetUrl };
              } else {
                // String URL (CKEditor mode)
                const url = assetOrUrl as string;
                const relativePath = url.startsWith('http') 
                  ? new URL(url).pathname 
                  : url;
                newPages[editingPageIndex] = { ...newPages[editingPageIndex], ogImage: relativePath || url };
              }
              setSeo({ ...seo, pages: newPages });
            }
            setPagePickerOpen(false);
          }}
          multiple={false}
        />
      )}
    </div>
  );
}

